### PR TITLE
Fix compilation error in CoordinatorBasicAuthorizerResourceTest

### PR DESCRIPTION
**Pull request by jon-wei**
Fixes a conflict between #7635 and #7661, this wasn't caught as both PRs compiled fine individually had completed their CI runs.

### CODE REVIEW

**Comment by himanshug** [comment]
this was failing my PR build and I was scratching my head :)
