### PR TITLE
Don't inadvertently exclude hadoop-client-core dependency

### LINKED ISSUE #8338: Missing hadoop client dependency
### Affected Version
Noticed in version 0.14.2, looks like it affects version 0.14.0 through to 0.15.1

### Description

Upgrading out test clusters to 0.14.2 resulted in Hadoop Ingestion Tasks failing with the below stack trace. It looks like since 0.14.0 the dependency hadoop-mapreduce-client-core-{$version}.jar is no longer present in the extension druid-hdfs-storage.

This dependency is present in the hadoopDependencies folder, however if my understanding of the classloader code is right, we purposefully do not include these jars in the mapreduce job's classpath.

Looks related to #6828 and  #6967
`java.lang.NoSuchMethodError: org.apache.hadoop.mapreduce.jobhistory.EventWriter.<init>(Lorg/apache/hadoop/fs/FSDataOutputStream;)V
	at org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler.createEventWriter(JobHistoryEventHandler.java:420) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler.setupEventWriter(JobHistoryEventHandler.java:459) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler.handleEvent(JobHistoryEventHandler.java:549) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at org.apache.hadoop.mapreduce.jobhistory.JobHistoryEventHandler$1.run(JobHistoryEventHandler.java:318) ~[hadoop-mapreduce-client-app-2.7.3.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]`

### PR DESCRIPTION
**Pull request by Dylan1312**
Fixes #8338.

I'm not hugely experienced with maven but it looks like by marking the client-core dependency as provided in indexing-service it's being skipped over in hdfs-storage. 

This PR removes references to hadoop-client-core that were introduced in #6828 and bumps the scope of hadoop-client in the indexing-service so that each submodule is depending on the same thing.

Open to alternatives if anyone with more expertise in maven knows a better fix.

Initial testing looks like this fixes the issue but currently getting this to deployed to our test cluster and will update with results.

<hr>

This PR has:
- [ x] been self-reviewed.

<hr>

### CODE REVIEW

**Comment by clintropolis** [comment]
Hi @Dylan1312, apologies for the delay into looking at this, could you provide some additional details about which Hadoop distribution/version and index task configuration that lead to encountering this issue? 

I don't seem to have a problem on indexing or historical side if I use the docker container we provide for the Hadoop quick-start tutorial, which admittedly is hardly a realistic test, but word on the street is that releases greater than 0.14.0 work for at least some versions of Hadoop besides the version we bundle by default (2.8.3).

I pulled your branch, and I can't quite tell what this patch would change; in terms of raw jars, a build of this branch appears identical to current master. But, I am also not incredibly familiar with the Hadoop index task class loader stuff, so maybe I'm missing something important in that regards? I'll try to have a closer look and see if I can get a better idea of what specifically is going on in there.

**Comment by Dylan1312** [comment]
Hey @clintropolis, no problem at all and thanks for looking! Happy to bump the milestone on this since we haven't heard of anyone else that's affected.

We're using a Cloudera distro of 2.6. I can get a full example of an indexing spec but I think the most pertinent thing that's potentially different is setting mapreduce.job.classloader = true (to avoid a jackson dependency conflict). Guessing that without classloader isolation the missing classes would be present in the hadoop install itself.

Example below showing the difference between a build of this branch and our latest release, note hadoop-mapreduce-client-core-2.8.3.jar isn't present within druid-hdfs-storage in the latter.

`➜  ls apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce*

apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce-client-app-2.8.3.jar
apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce-client-common-2.8.3.jar
apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce-client-core-2.8.3.jar
apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce-client-jobclient-2.8.3.jar
apache-druid-0.16.0-incubating-SNAPSHOT/extensions/druid-hdfs-storage/hadoop-mapreduce-client-shuffle-2.8.3.jar

➜  ls ~/Downloads/apache-druid-0.15.1-incubating/extensions/druid-hdfs-storage/hadoop-mapreduce*

/Users/dylan/Downloads/apache-druid-0.15.1-incubating/extensions/druid-hdfs-storage/hadoop-mapreduce-client-app-2.8.3.jar
/Users/dylan/Downloads/apache-druid-0.15.1-incubating/extensions/druid-hdfs-storage/hadoop-mapreduce-client-common-2.8.3.jar
/Users/dylan/Downloads/apache-druid-0.15.1-incubating/extensions/druid-hdfs-storage/hadoop-mapreduce-client-jobclient-2.8.3.jar
/Users/dylan/Downloads/apache-druid-0.15.1-incubating/extensions/druid-hdfs-storage/hadoop-mapreduce-client-shuffle-2.8.3.jar`

That JAR is present in the hadoop-dependencies folder but as far as I can tell we don't include that folder in the classloader that's set up for the hadoop container.
